/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TransactionFilterOptions {
  typePatterns?: Array<string>
  fetchAllDeleteTableItem?: boolean
}
export declare function startFetchTransactions(url: string, authKey: string | undefined | null, startVersion: bigint, endVersion?: bigint | undefined | null, filterOptions?: TransactionFilterOptions | undefined | null): Promise<number>
export declare function nextTransactions(ch: number): Promise<string | null>
export declare function sum(a: number, b: number): number
